In [2]:
import torch
import torch.nn as nn
import math

class InputEmbeddings(nn.Module):

    def __init__(self, d_model: int, vocab_size: int):
        super().__init__()
        self.d_model = d_model
        self.vocab_size = vocab_size
        self.embedding = nn.Embedding(vocab_size, d_model)

    def forward(self,x):
        return self.embedding(x) 
    

# if __name__ == "__main__":
obj = InputEmbeddings(512,10000)


In [12]:
print(obj.embedding.weight)

Parameter containing:
tensor([[ 6.0430e-01,  7.5955e-01,  5.9045e-01,  ...,  3.4396e-01,
          3.1660e-01, -1.1293e-01],
        [ 2.5945e+00, -1.1159e+00, -8.2287e-01,  ..., -9.9228e-01,
         -1.5557e-01,  9.0564e-01],
        [-2.9468e+00, -1.3252e-01, -7.7744e-01,  ...,  5.0423e-01,
         -1.3313e+00,  5.3194e-01],
        ...,
        [ 3.2879e-01, -4.3352e-01, -6.9503e-01,  ..., -2.3205e-01,
          1.9717e+00,  1.0405e+00],
        [-1.7839e+00, -5.0261e-01, -7.4572e-01,  ..., -4.8847e-01,
         -1.3671e+00, -6.4738e-01],
        [-2.4026e-03,  6.7048e-01, -1.0378e-02,  ..., -3.1983e-01,
         -1.7940e-01, -9.8755e-01]], requires_grad=True)


In [18]:
import torch
x = torch.tensor([1, 2, 3])
print(x.shape)  # torch.Size([3])
print(x)
x_unsqueezed = x.unsqueeze(0)  # Add a new dimension at dim=0
print(x_unsqueezed.shape)  # torch.Size([1, 3])
print(x_unsqueezed)
# x_unsqueezed = x.unsqueeze(1)  # Add at dim=1
# print(x_unsqueezed.shape)  # torch.Size([3, 1])
# print(x_unsqueezed)

torch.Size([3])
tensor([1, 2, 3])
torch.Size([1, 3])
tensor([[1, 2, 3]])


In [19]:
x_unsqueezed[0][1]

tensor(2)